language: java

install: mvn clean install --quiet -DskipTests=true

script: mvn clean test -P integration-tests

after_success: mvn cobertura:cobertura coveralls:cobertura

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61d61757ee57d30e343b
    on_success: change
    on_failure: always
    on_start: falsebefore_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
